main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('work/', views.work, name='work'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('schedule/', include('story5.urls')),
    path('accordion/', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('user/', include('story9.urls')),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
    
]

story9/models.py
from django.db import models
# from django.contrib.auth.models import User

# Create your models here.

# class UserModels(models.Model):
#     username = models.OneToOneField(User, max_length=20, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=200)
#     last_name = models.CharField(max_length=200)
#     email = models.EmailField(max_length=200)

#     def __str__(self):
#         return self.username

story9/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

story9/views.py
from django.shortcuts import render, redirect # redirect for login register
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm # for register n login form

from django.contrib.auth import authenticate, login, logout # for login

from django.contrib import messages # added for login register

from django.contrib.auth.models import Group

from .forms import CreateUserForm

from django.contrib.auth.decorators import login_required

# Create your views here.


def registerPage(request):
    if request.user.is_authenticated:
        return redirect('story9:index')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user = form.save()
                username = form.cleaned_data.get('username')

                messages.success(request, 'Account was created for ' + username)

                return redirect('story9:login')

        context = {'form':form}
        return render(request, 'story9/register.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('story9:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('story9:index')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'story9/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('story9:login')

@login_required(login_url='/user/login')
def index(request):
	return render(request, 'story9/index.html')

story9/templates/story9/index.html
{% extends "main/base.html" %}
{% load static %}
{% block meta %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock meta %}

{% block content %}

    <!--   Header   -->
    <div class="page-header header-filter clear-filter" data-parallax="true" style="background-image: url({% static 'main/img/header-background.png'%});">
        <div class="container">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <div class="brand">
                        <h1 class="title">Welcome to da Club! 🦄</h1>
                        <h3 class="title">This is where the adventure begins 🐾</h3>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--   AJAX Book GoogleAPIS  -->
    <div class="main main-raised">
        <div class="container" id="container">
            <br><br><br><br>
            <h2 class="text-center title">Hi, {{ user.username }} 👋🏻</h2>
            <br><br>

            <h3 class="text-center"> Looking for an adventure? </h3>
            <p  class="text-center">Get up, pack up and get yourself ready for the journey ahead!</p>
            <p  class="text-center">But if you're feeling it's not the day, it's okay. Take a rest for a while and get yourself ready for tomorrow journey 🤗</p>
            <br><br><br>
            <div class="row">
                            <div class="col-md-12 ml-auto mr-auto text-center">
                                <a type="button" class="btn btn-primary btn-raised" href="{% url 'story9:logout' %}">
                                    See you tomorrow!
                                </a>
                            </div>
                        </div>
            <br><br><br><br>
        </div>
    </div>

    <div class="container">
        
        

    </div>

</body>
{% endblock content %}

story9/templates/story9/login.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <!-- Fonts -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" />
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<!-- CSS StyleSheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/registerLogin.css' %}">



</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Welcome to da Club!</h3>
				</div>
				<div class="d-flex justify-content-center">
					<p>Please login first</p>
				</div>
				
					
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username" class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password" class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<div class="alert {{ message.tags }} alert-success" role="alert">
						{{message}}
					</div>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'story9:register' %}" class="ml-2 links-text">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

story9/templates/story9/register.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Sign Up</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <!-- Fonts -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" />
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<!-- CSS StyleSheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/registerLogin.css' %}">

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">SIGN UP</h3>
				</div>
				<div class="d-flex justify-content-center">
					<p>Sign up to join da adventure!</p>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Sign Up">
				   		</div>

					</form>
				</div>


				{% if form.errors %}
					{% for field in form %}
						{% for error in field.errors %}
							<div class="alert alert-danger">
								{{ error|escape }}
							</div>
						{% endfor %}
					{% endfor %}
					{% for error in form.non_field_errors %}
						<div class="alert alert-danger">
							{{ error|escape }}
						</div>
					{% endfor %}
				{% endif %}

				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'story9:login' %}" class="ml-2 links-text">Login</a>
					</div>
				</div>
			</div>
		</div>
		
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username';
		form_fields[2].placeholder='Email';
		form_fields[3].placeholder='Enter password';
		form_fields[4].placeholder='Re-enter Password';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	
	</script>
</body>
</html>