main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('work/', views.work, name='work'),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('schedule/', include('story5.urls')),
    path('accordion/', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('user/', include('story9.urls')),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('list/', views.schedule_list, name='schedule_list'),
    path('add/', views.add_schedule, name='add_schedule'),
    path('list/details/<int:index>', views.course_details, name='course_details'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.accordion, name='accordion'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.books, name='books'),
    path('data/', views.search_book, name='search_book'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
    
]

story7/models.py
from django.db import models

# Create your models here.

story7/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
	return render(request, 'story7/accordion.html')

story7/templates/story7/accordion.html
{% extends 'story7/base_story7.html' %}
{% load static %}
{% block meta %}
{% endblock meta %}


{% block content %}

<!--   Header   -->
    <div class="page-header header-filter clear-filter" data-parallax="true" style="background-image: url({% static 'main/img/header-background.png'%});">
        <div class="container">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <div class="brand">
                        <h1 class="title">Here we are, at Story 7 &#9924;</h1>
                        <h2 class="title">Let's explore more! </h2>
                        <h3 class="title">But not too far, <br/>
                        or you'll be drowned.</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--   Acoordion  -->
    <div class="main main-raised">
        <div class="container" id="container">
            <br><br><br><br>
            <h2 class="text-center title">A 'lil 'bout Me</h2>
            <br><br>

            <div class="accordion-container">
                <div id="activity" class="set">
                    <a href="#container" class="bar d-flex justify-content-between">
                        Current Activity 
                        <div>
                            <button class="up">▲</button>
                            <span>&ensp;</span>
                            <button class="down">▼</button>
                        </div>
                    </a>

                    <div class="content">
                        <p> → Breathing </p>
                        <p> → Struggling </p>
                    </div>
                </div>

                <div id="experience" class="set">
                    <a href="#container" class="bar d-flex justify-content-between">
                        Experience
                        <div>
                            <button class="up">▲</button>
                            <span>&ensp;</span>
                            <button class="down">▼</button>
                        </div>
                    </a>

                    <div class="content">
                        <p> Staff of Public Relation Bureau of FUKI Fasilkom UI </p>
                        <p> Treasurer of SIWAK-NG 2020 </p>
                        <p> ... </p>
                    </div>
                </div>
                
                <div id="achievement" class="set">
                    <a href="#container" class="bar d-flex justify-content-between">
                        Achievement
                        <div>
                            <button class="up">▲</button>
                            <span>&ensp;</span>
                            <button class="down">▼</button>
                        </div>
                    </a>

                    <div class="content">
                        <p> Still breathing and counting (+working on it)</p>
                    </div>
                </div>
                
                <div id="contact" class="set">
                    <a href="#container" class="bar d-flex justify-content-between">
                        Contact
                        <div>
                            <button class="up">▲</button>
                            <span>&ensp;</span>
                            <button class="down">▼</button>
                        </div>
                    </a>
                    
                    <div class="content">
                        <p> <a href="{% url 'main:home' %}#contact" target="_blank">Find me in here</a> </p>
                    </div>
                </div>
            </div>
            <br><br><br><br>
        </div>
    </div>


{% block script %}<script src="{% static 'story7/js/accordion.js' %}"></script>{% endblock %}

{% endblock %}

story7/templates/story7/base_story7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>My Accordion</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  
  <!--     Fonts and icons     -->
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'main/img/logo.svg'%}">
  <link rel="icon" type="image/png" href="{% static 'main/img/logo.svg'%}">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
  <!-- CSS Files -->
  <link rel="stylesheet" href="{% static 'main/css/material-kit.css?v=2.0.7' %}">
  <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'story7/css/accordion.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body class="sidebar-collapse">
  <!--   Navbar  -->
	<nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="{% url 'main:home'%}">
          <div class="logo-image">
            <img src="{% static 'main/img/logo.svg'%}" class="img-fluid">
          </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:home' %}#profile">
              PROFILE
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:home' %}#education">
              EDUCATION
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:home' %}#experience">
              EXPERIENCE
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:work'%}">
              WORK
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:home' %}#contact">
              CONTACT
            </a>
          </li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <span class="material-icons">filter_vintage</span>
            </a>
            <div class="dropdown-menu dropdown-with-icons">
              <a href="{% url 'story9:index'%}" class="dropdown-item">
                <span class="material-icons">book</span> User
              </a>
              <a href="{% url 'story8:books'%}" class="dropdown-item">
                <span class="material-icons">book</span> Book World
              </a>
              <a href="{% url 'story7:accordion'%}" class="dropdown-item">
                <span class="material-icons">book</span> My Accordion
              </a>
              <a href="{% url 'story5:schedule_list'%}" class="dropdown-item">
                <span class="material-icons">book</span> Schedule
              </a>
              <a href="{% url 'story1:story1'%}" class="dropdown-item" target="_blank">
                <span class="material-icons">book</span> Story 1
              </a>
              <a href="#" class="dropdown-item">
                <span class="material-icons">bedtime</span> Coming Really Soon 
              </a>
            </div>
          </li>
          <li>
            {% if user.is_authenticated == False %}
              <a class="nav-link active" type="submit" href="{% url 'story9:login'%}">Log in</a>
              
            {% else %}
              <a class="nav-link active" type="submit" href="{% url 'story9:logout'%}">Log out</a>
            {% endif %}
				  </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}

  <!--   Footer   -->
  <footer class="footer footer-default">
    <div class="container">
      <div class="copyright">
        Build with &#128156 by Aisha
      </div>
      <div class="copyright">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script>, <a href="https://www.creative-tim.com/" target="_blank">Creative Tim</a> <br>
        Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
      </div>
    </div>
  </footer>
  <!--   Core JS Files   -->
  <script src="{% static 'main/js/core/jquery.min.js'%}" type="text/javascript"></script>
  <script src="{% static 'main/js/core/popper.min.js'%}" type="text/javascript"></script>
  <script src="{% static 'main/js/core/bootstrap-material-design.min.js'%}" type="text/javascript"></script>
  <script src="{% static 'main/js/plugins/moment.min.js'%}"></script>
  <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="{% static 'main/js/plugins/bootstrap-datetimepicker.js'%}" type="text/javascript"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'main/js/plugins/nouislider.min.js'%}" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'main/js/material-kit.js?v=2.0.7'%}" type="text/javascript"></script>
  <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>

  {% block script %}{% endblock %}

</body>

</html>