main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('work/', views.work, name='work'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('schedule/', include('story5.urls')),
    path('accordion/', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('user/', include('story9.urls')),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('list/', views.schedule_list, name='schedule_list'),
    path('add/', views.add_schedule, name='add_schedule'),
    path('list/details/<int:index>', views.course_details, name='course_details'),
]

story5/models.py
from django.db import models

# Create your models here.
# Details of the Schedule (course, lecturer, credit(s), term, desc, room)
class Schedule(models.Model):
    course = models.CharField(max_length=150, null=True)
    lecturer = models.CharField(max_length=150, null=True)
    credit = models.IntegerField(null=True)
    term = models.CharField(max_length=150, null=True)
    description = models.TextField(max_length=350, null=True)
    classroom = models.CharField(max_length=150, null=True)

story5/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.Form):
    
    course = forms.CharField(
        label = 'Course', 
        max_length = 100, 
        required = True,
        widget = forms.TextInput(
            attrs ={'class': 'form-control'}),
    )

    lecturer = forms.CharField(
        label = 'Lecturer', 
        max_length = 100, 
        required = True,
        widget = forms.TextInput(
            attrs ={'class': 'form-control'}),
    )

    credit = forms.IntegerField(
        label = 'Credits', 
        required = True,
        widget = forms.NumberInput(
            attrs ={'class': 'form-control'}),
    )

    term = forms.CharField(
        label = 'Term', 
        max_length = 100, 
        required = True,
        widget = forms.TextInput(
            attrs ={'class': 'form-control'}),
    )

    classroom = forms.CharField(
        label = 'Classroom', 
        max_length = 100, 
        required = True,
        widget = forms.TextInput(
            attrs ={'class': 'form-control'}),
    )

    description = forms.CharField(
        label = 'Description', 
        max_length = 150, 
        required = True,
        widget = forms.Textarea(
            attrs ={'class': 'form-control', 'rows': '4'}),
    )

story5/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from .models import Schedule
from .forms import ScheduleForm
from story5 import forms, models

# Create your views here.

def add_schedule(request):
    schedule = Schedule.objects.all().values()
    form = ScheduleForm(request.POST or None)
    context = {
        'schedule': schedule,
        'form': form,
        }
    if request.method == "POST":
        if form.is_valid():
            schedule.create(
                course = form.cleaned_data.get('course'),
                lecturer = form.cleaned_data.get('lecturer'),
                credit = form.cleaned_data.get('credit'),
                description = form.cleaned_data.get('description'),
                term = form.cleaned_data.get('term'),
                classroom = form.cleaned_data.get('classroom'),
            )
        return redirect('/schedule/list')
           
    return render(request, 'add_schedule.html', context)

def schedule_list(request):
    schedule = Schedule.objects.all().values()
    context = {'schedule': schedule}
    if request.method == "POST":
        if 'id' in request.POST:
            Schedule.objects.get(id=request.POST['id']).delete()
            return redirect('/schedule/list')
    list_course = Schedule.objects.all()
    return render(request, 'schedule_list.html', context)

def course_details(request, index):
    schedule = Schedule.objects.get(pk=index)
    context = {'schedule':schedule}
    return render(request, 'course_details.html', context)

story5/templates/add_schedule.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}
    <!--   Header   -->
    <div class="page-header header-filter clear-filter" data-parallax="true" style="background-image: url({% static 'main/img/header-background.png'%});">
        <div class="container">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <div class="brand">
                        <h1 class="title" style="display:inline">Feeling overwhelmed by your activities?</h1>
                        <p style="display:inline"><a href="{% static 'story5/img/support.gif'%}" target="_blank"><s>click here</s></a></p>
                        <h2 class="title">Let's schedule-it-up!</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--   Add Schedule Form   -->
    <div class="main main-raised">
        <div class="container">
            <div class="section section-contacts">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto">
                        <h2 class="text-center title">Add a Schedule</h2>
                        <h4 class="text-center description">Even though you're not visiting this web regularly, let's scheduling our course/activities here so that we can support and remind each other 🤗</h4>
                        <form class="contact-form" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="row justify-content-center">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">{{ field.label }}</label>
                                            {{ field }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="row">
                                <div class="col-md-6 ml-auto mr-auto text-center">
                                    <input type="submit" value="Submit" class="btn btn-primary btn-raised">
                                </div>
                            </div>
                        </form>
                        <br/><br/><br/><br/><br/>
                        <div class="row">
                            <div class="col-md-12 ml-auto mr-auto text-right">
                                <a type="button" class="btn btn-primary btn-raised" href="{% url 'story5:schedule_list' %}">
                                    Schedule List
                                </a>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

story5/templates/course_details.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}
    <!--   Header   -->
    <div class="page-header header-filter clear-filter" data-parallax="true" style="background-image: url({% static 'main/img/header-background.png'%});">
        <div class="container">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <div class="brand">
                        <h1 class="title" style="display:inline">Feeling overwhelmed by your activities?</h1>
                        <p style="display:inline"><a href="{% static 'story5/img/support.gif'%}" target="_blank"><s>click here</s></a></p>
                        <h2 class="title">Let's schedule-it-up!</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--   Schedule Details   -->
    <div class="main main-raised">
        <div class="container">
            <div class="section section-contacts" id="schedule">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto">
                        <h2 class="text-center title">Schedule Details</h2>
                        <br><br><br>
                        <div class="card card-nav-tabs">
                            <div class="card-header card-header-primary text-center">
                                <h3 class="title text-uppercase" style="letter-spacing: 0.1em;"><strong>{{ schedule.course }}</strong></h3>
                            </div>
                            <div class="card-body">
                                <h4 class="card-text"><strong>Lecturer</strong></h4>
                                <p class="card-text">{{ schedule.lecturer }}</p>
                                <h4 class="card-text"><strong> Credits</strong></h4>
                                <p class="card-text">{{ schedule.credit }}</p>
                                <h4 class="card-text"><strong>Term</strong></h4>
                                <p class="card-text">{{ schedule.term }}</p>
                                <h4 class="card-text"><strong>Classroom</strong></h4>
                                <p class="card-text">{{ schedule.classroom }}</p>
                                <h4 class="card-text"><strong>Description</strong></h4>   
                                <p class="card-text">{{ schedule.description }}</p>
                                <br>
                                <a href="{% url 'story5:schedule_list' %}" class="btn btn-primary">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

story5/templates/schedule_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}
    <!--   Header   -->
    <div class="page-header header-filter clear-filter" data-parallax="true" style="background-image: url({% static 'main/img/header-background.png'%});">
        <div class="container">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <div class="brand">
                        <h1 class="title" style="display:inline">Feeling overwhelmed by your activities?</h1>
                        <p style="display:inline"><a href="{% static 'story5/img/support.gif'%}" target="_blank"><s>click here</s></a></p>
                        <h2 class="title">Let's schedule-it-up!</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--   Schedule List   -->
    <div class="main main-raised">
        <div class="container">
            <br><br><br><br>
            <h2 class="text-center title">Schedule List</h2>
            <br><br><br>
            <div class="table-responsive table-borderless">
                <table class="table table-hover text-center">
                    <thead>
                        <tr class="text-center">
                            <th scope="col"><h4><b>Course</b></h4></th>
                            <th scope="col"><h4><b>Lecturer</b></h4></th>
                            <th scope="col"><h4><b>Credits</b></h4></th>
                            <th scope="col"><h4><b>Room</b></h4></th>
                            <th scope="col">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% csrf_token %}
                        {% for course in schedule %}
                        <tr>
                            <td scope="row"><a href="details/{{ course.id }}"><strong>{{ course.course }}</strong></a></td>
                            <td>{{ course.lecturer }}</td>
                            <td>{{ course.credit }}</td>
                            <td>{{ course.classroom }}</td>
                            <td>
                                <form method="POST" action="">
                                    {% csrf_token %}
                                    <input name="id" value="{{ course.id }}" type="hidden">                        
                                    <button type="submit" value="Submit" class="btn btn-default">Delete</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <br><br><br><br>
            <div class="row">
                <div class="col-md-12 ml-auto mr-auto text-center">
                    <a type="button" class="btn btn-primary btn-raised" href="{% url 'story5:add_schedule' %}">
                        Add New Schedule
                    </a>
                </div>
            </div>
            <br><br><br><br>

        </div>
    </div>
{% endblock content %}